// counter
export const COUNTER_SET_VALUE = 'COUNTER_SET_VALUE'
export const COUNTER_SET_DISPLAY_VIEW = 'COUNTER_SET_DISPLAY_VIEW'
export const COUNTER_INCREASE_VALUE = 'COUNTER_INCREASE_VALUE'
export const COUNTER_SET_START_VALUE = 'COUNTER_SET_START_VALUE'
export const COUNTER_SET_MAX_VALUE = 'COUNTER_SET_MAX_VALUE'
